app:
  id: ${random.uuid}
  name: "iam"
  consul:
    hostname: "localhost"
    port: 8500

spring:
  main:
    banner-mode: "off"
  application:
    name: "iam"
    java:
      version: "@java.version@"
  jmx:
    enable: false
  data:
    mongodb.host: "mongo"
    mongodb.port: 27017
    mongodb.database: "prod"
    
producer:
    file: "input.txt"
    input-topic: "input-topic"
    output-topic: "output-topic"
    enedis-topic: "enedis-topic"
    sound-topic: "sound-topic"
    

server:
  port: 8080

