version: "2"
services:
  zookeeper:
    image: "confluentinc/cp-zookeeper:3.2.1"
    container_name: "zookeeper"
    hostname: "zookeeper"
    environment:
        - ZOOKEEPER_CLIENT_PORT=32181
    volumes:
        - ./zookeeper/data:/var/lib/zookeeper/data
        - ./zookeeper/logs:/var/lib/zookeeper/log
    ports:
        - "32181:32181"
  kafka:
    image: "confluentinc/cp-kafka:3.2.1"
    container_name: "kafka"
    hostname: "kafka"
    depends_on:
      - zookeeper
    environment:
        - KAFKA_BROKER_ID=1
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:32181
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092
    volumes:
        - ./kafka/data:/var/lib/kafka/data
    ports:
        - "29092:29092"
  shema_registry:
    image: "confluentinc/cp-schema-registry:3.2.1"
    container_name: "schema-registry"
    hostname: "schema-registry"
    depends_on:
      - kafka
    environment:
        - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:32181
        - SCHEMA_REGISTRY_HOST_NAME=schema-registry
        - SCHEMA_REGISTRY_LISTENERS=http://localhost:8581
    ports:
        - "8581:8581"
  neo4j:
    image: "neo4j:3.0"
    container_name: "neo4j"
    hostname: "neo4j"
    volumes:
        - ./neo4j/data:/data
        - ./neo4j/import:/var/lib/neo4j/import
        - ./neo4j/logs:/logs
    ports:
        - "7474:7474"
        - "7687:7687"
        - "7473:7473"
