app:
  id: ${random.uuid}
  name: "iam"
  consul:
    hostname: "localhost"
    port: 8500

spring:
  main:
    banner-mode: "off"
  application:
    name: "iam"
    java:
      version: "@java.version@"
  jmx:
    enable: false
  data:
    mongodb.host: "mongo"
    mongodb.port: 27017
    mongodb.database: "prod"
    
server:
    port: 8443
    ssl:
        key-store: keystore.p12
        key-store-password: password
        keyStoreType: PKCS12
        keyAlias: tomcat
  

keystore:
  file: keystore.jks
  pass: password
  

